### ISSUE TITLE
Error converting '-3' to ProgramBuildStatus.

### ISSUE THREAD

**Issue by webmaster128** [cogciprocate/ocl#130]
When trying to monitor the build status using ocl-core, I get the error

```
Build started
thread '<unnamed>' panicked at 'error: Error converting '-3' to ProgramBuildStatus.', libcore/result.rs:1009:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::char::methods::<impl char>::escape_debug
             at libcore/panicking.rs:77
   8: core::ptr::swap_nonoverlapping_bytes
             at /rustc/13c9439925797cd7a65c917d047c07a500d9bfe6/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /rustc/13c9439925797cd7a65c917d047c07a500d9bfe6/src/libcore/result.rs:835
  10: lisk_vanity::gpu::Gpu::new::{{closure}}
             at src/gpu.rs:99
```

after sucessfully compiling this code

```rust
        let strings = program_builder.get_src_strings().unwrap();
        let program = core::create_program_with_source(&context, &strings)
            .expect("Error creating source");
        let program2 = program.clone();
        let cmplr_opts = CString::new("").unwrap();

        thread::spawn(move || loop {
            // some work here
            let status = core::get_program_build_info(
                &program, device, core::ProgramBuildInfo::BuildStatus
                ).expect("error");
            let log = core::get_program_build_info(
                &program, device, core::ProgramBuildInfo::BuildLog
                ).expect("error");
            eprintln!("Status: {}; Log: {}", status, log);
            thread::sleep(Duration::from_millis(1000));
        });

        eprintln!("Build started");
        core::build_program(
            &program2, Option::Some(&[device]),
            &cmplr_opts, None, None)
            .expect("Could not build");
        eprintln!("Build ended");
```

where line 99 is

```rust
            let status = core::get_program_build_info(
```

Yesterday I got a very similar error with -1 instead of -3 when the code was arranged a little different.

-----

Update: this happens in both

> GPU platform Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing
> Using GPU device Advanced Micro Devices, Inc. gfx900, OpenCL 1.2

and 

> GPU platform Apple Apple
> Using GPU device Intel Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz, OpenCL 1.2

**Comment by c0gent** [comment]
210d85f3544a56b7c633945c9a73cd29b7d44e48 should fix. 

Please try again with the latest version on master and let me know :)

**Comment by webmaster128** [comment]
Thanks @c0gent. Can I somehow use master as a dependency in Cargo.toml?

**Comment by dmarcuse** [comment]
There's a special syntax for using git dependencies, described [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)

**Comment by webmaster128** [comment]
Thanks! I had to change the version of both ocl-core and ocl because otherwise the old ocl-core was linked. But now it works like a charm:

```
[...]
GPU context created.
GPU queue created.
Build started
Status: None; Log: ''
Status: InProgress; Log: ''
Status: InProgress; Log: ''
Status: InProgress; Log: ''
Status: InProgress; Log: ''
Status: InProgress; Log: ''
Status: InProgress; Log: ''
Status: InProgress; Log: ''
Build ended
Status: Success; Log: ''
Status: Success; Log: ''
Status: Success; Log: ''
[...]
```

**Comment by webmaster128** [comment]
Fixed on master, closing, thanks!

**Comment by c0gent** [comment]
Thank you!
