### ISSUE TITLE
OS X panic in events example

### ISSUE THREAD

**Issue by neverfox** [cogciprocate/ocl#60]
As mentioned in #9, the events example panics (on OS X with an Intel Iris Pro GPU, in this case). Here's the output:

```
Enqueuing kernel [itr:0]...
Enqueuing read buffer [itr:0]...
Setting callback (verify_result, buncha_stuff[0]) [i:0]...
Enqueuing kernel [itr:1]...
Enqueuing read buffer [itr:1]...

Event: `0x7fadd33004d0` has completed with status: `0`, data_set_size: '262144`, addend: 11, itr: `0`.
correct_result: 448, result_vec[0]:448
correct_result: 18, result_vec[1]:18
correct_result: 261, result_vec[2]:261
correct_result: 213, result_vec[3]:213
correct_result: 488, result_vec[4]:488
Setting callback (verify_result, buncha_stuff[1]) [i:1]...
Enqueuing kernel [itr:2]...

Event: `0x7fadd0d0a3b0` has completed with status: `0`, data_set_size: '262144`, addend: 11, itr: `1`.
correct_result: 459, result_vec[0]:459
correct_result: 29, result_vec[1]:29
correct_result: 272, result_vec[2]:272
correct_result: 224, result_vec[3]:224
correct_result: 499, result_vec[4]:499
Enqueuing read buffer [itr:2]...
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `317`, right: `306`)', examples/events.rs:52
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Setting callback (verify_result, buncha_stuff[2]) [i:2]...
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `265`, right: `254`)', libc++abi.dylib: examples/events.rs:52
terminating with uncaught foreign exceptionEnqueuing kernel [itr:3]...


Event: `0x7fadd33008d0` has completed with status: `0`, data_set_size: '262144`, addend: 11, itr: `2`.
libc++abi.dylib: %
```

**Comment by c0gent** [comment]
Nvidia by chance?

**Comment by neverfox** [comment]
Intel Iris Pro (at least, I don't think Intel is just Nvidia under a different label, but I can't be sure). I assume you're recognizing the similarity to the panic in #26, which I noticed too.

**Comment by c0gent** [comment]
Ok I'll make a note about buggyness on that hardware platform too.

There's nothing for you to worry about as long as you don't use event callbacks. I'll be adding [futures-rs](https://github.com/alexcrichton/futures-rs) integration soon which should eliminate the need to even use those callbacks.

Thanks for the report.
