### ISSUE TITLE
Panic when no OpenCL platform is found

### ISSUE THREAD

**Issue by YaLTeR** [cogciprocate/ocl#74]
I'm making a context with `Context::builder()`.

`Platform::default()` [here](https://github.com/cogciprocate/ocl/blob/master/src/standard/platform.rs#L176) panics if no default platform was found. On my laptop it gives me the error:
```
thread '<unnamed>' panicked at 'Platform::default(): core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 0 seconds of waiting.'
```
(the 0 seconds part is another mistake in `core::get_platform_ids()` but it's irrelevant to this issue)

I'm not sure if my laptop supports OpenCL but even if it doesn't I'd like this to return an `Err` and not to panic, as this seems to be the recommended way of creating an OpenCL context.

**Comment by c0gent** [comment]
Apologies for being so slow to respond. It's a busy time of year for me. I'm out of town this weekend and I have another trip early next week. I'll get to the bottom of this issue as soon as I get back. :)

**Comment by c0gent** [comment]
https://github.com/cogciprocate/ocl-core/commit/75bcda05dd2a496591909eb9ca919c4543a8f1fc should fix the error message time.

If you need to create a context without the possibility of a panic when checking for platforms, use something like the following:

```
// Handle error as needed:
let plat = ocl::core::default_platform().unwrap();

let context = Context::builder()
  .platform(plat)
  ...
```

Let me know if that works.

**Comment by YaLTeR** [comment]
Yeah, this is close to what I ended up doing.

**Comment by c0gent** [comment]
Thanks for filing the issue. Let me know if there's anything else or feel free to ask general questions here: https://gitter.im/cogciprocate/ocl.

**Comment by c0gent** [comment]
@YaLTeR: I'll post this here as well in case you don't see the gitter chat:

cogciprocate/ocl@202fd9f should replace all occurrences of `Platform::default` with the new `Platform::first` method. When you have time, please pull the latest ocl master branch and try `Context::builder`... on your system (I'm not inclined to mess with my OpenCL platform drivers right now to test). Let me know that it returns an error instead of panicking. If you don't mind, could you also run a `cargo test` and the `examples/runall.sh` script and let me know if the error messages you get are clear enough?

**Comment by YaLTeR** [comment]
`Context::builder()` and `ProQue::builder()` seem to be returning `Err` as they should (no panics). This is the output of `cargo test`:
```
running 13 tests
test tests::async::rw_vec ... FAILED
test tests::buffer_copy::buffer_copy_core ... FAILED
test tests::buffer_fill::fill ... FAILED
test tests::buffer_copy::buffer_copy_standard ... FAILED
test tests::build_error::bad_kernel_variable_names ... ok
test tests::buffer_ops_rect::buffer_ops_rect ... FAILED
test tests::buffer_fill::fill_with_float4 ... FAILED
test tests::clear_completed::clear_completed ... FAILED
thread '[thread_0]' panicked at 'Platform::list: Error retrieving platform list: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859
test tests::image_ops::image_ops ... FAILED
thread '[thread_1]' panicked at 'Platform::list: Error retrieving platform list: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859test tests::kernel_arg_ptr::kernel_arg_ptr_out_of_scope ... 
FAILED
test tests::context_props::test_context_props ... FAILED
test tests::concurrent::concurrent ... FAILED
test tests::vector_types::test_vector_types ... FAILED

failures:

---- tests::async::rw_vec stdout ----
	thread 'tests::async::rw_vec' panicked at 'Platform::list: Error retrieving platform list: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::buffer_copy::buffer_copy_core stdout ----
	thread 'tests::buffer_copy::buffer_copy_core' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::buffer_fill::fill stdout ----
	thread 'tests::buffer_fill::fill' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::buffer_copy::buffer_copy_standard stdout ----
	thread 'tests::buffer_copy::buffer_copy_standard' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- tests::buffer_ops_rect::buffer_ops_rect stdout ----
	thread 'tests::buffer_ops_rect::buffer_ops_rect' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::buffer_fill::fill_with_float4 stdout ----
	thread 'tests::buffer_fill::fill_with_float4' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::clear_completed::clear_completed stdout ----
	thread 'tests::clear_completed::clear_completed' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::image_ops::image_ops stdout ----
	thread 'tests::image_ops::image_ops' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::kernel_arg_ptr::kernel_arg_ptr_out_of_scope stdout ----
	thread 'tests::kernel_arg_ptr::kernel_arg_ptr_out_of_scope' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::context_props::test_context_props stdout ----
	thread 'tests::context_props::test_context_props' panicked at 'Platform::list: Error retrieving platform list: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859

---- tests::concurrent::concurrent stdout ----
	Listing platforms 2 times...
thread 'tests::concurrent::concurrent' panicked at 'Error joining thread: '"[thread_0]"'', src/tests/concurrent.rs:44

---- tests::vector_types::test_vector_types stdout ----
	thread 'tests::vector_types::test_vector_types' panicked at 'called `Result::unwrap()` on an `Err` value: core::get_platform_ids(): CL_PLATFORM_NOT_FOUND_KHR... Unable to get platform id list after 10 seconds of waiting.', /checkout/src/libcore/result.rs:859


failures:
    tests::async::rw_vec
    tests::buffer_copy::buffer_copy_core
    tests::buffer_copy::buffer_copy_standard
    tests::buffer_fill::fill
    tests::buffer_fill::fill_with_float4
    tests::buffer_ops_rect::buffer_ops_rect
    tests::clear_completed::clear_completed
    tests::concurrent::concurrent
    tests::context_props::test_context_props
    tests::image_ops::image_ops
    tests::kernel_arg_ptr::kernel_arg_ptr_out_of_scope
    tests::vector_types::test_vector_types

test result: FAILED. 1 passed; 12 failed; 0 ignored; 0 measured

error: test failed, to rerun pass '--lib'
```

`runall.sh` outputs a bunch of unwraps on `Err` value as expected.

**Comment by c0gent** [comment]
Thanks again :)
