### ISSUE TITLE
trivial.rs fails with OpenCL 1.1

### ISSUE THREAD

**Issue by AdamNiederer** [cogciprocate/ocl#80]
Hello,

I'm using opencl-mesa (Feature Level 1.1) on an HD 7950, and `ocl = "0.14"`, and [the trivial example](https://github.com/cogciprocate/ocl/blob/811f817/examples/trivial.rs) is throwing an error at `let buffer = pro_que.create_buffer::<f32>().unwrap();`

It looks like `BufferBuilder` is exhibiting the same behavior. Is this a driver bug, or is OpenCL 1.1 not supported?

**Comment by c0gent** [comment]
It's possible there may be an issue with 1.1. I haven't tested it in a long time. I'll play around with the mesa drivers tonight or tomorrow. What's the error?

**Comment by AdamNiederer** [comment]
Here's what I get when running it:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OpenCL version too low to use this feature (detected: 1.1, required: 1.2).', /checkout/src/libcore/result.rs:860:4```

**Comment by c0gent** [comment]
I won't have time to debug this myself until Thursday or Friday but I the error is undoubtedly coming from [`::enqueue_fill_buffer`](https://docs.rs/ocl-core/0.5.1/ocl_core/fn.enqueue_fill_buffer.html) which is an OpenCL 1.2+ function. 

`ProQue::create_buffer` fills the buffer with zeros by default. Perhaps that needs to be changed. If you create a buffer without a fill value it should work fine (leave off the [`.fill_val(...)`](https://docs.rs/ocl/0.14.1/ocl/builders/struct.BufferBuilder.html#method.fill_val) part when using `BufferBuilder`). Let me know if that works.

Otherwise this needs either a better error message or just different default behavior.

**Comment by AdamNiederer** [comment]
I've replaced `let buffer = pro_que.create_buffer::<f32>().unwrap();` with the following expression:

```  
let buffer = BufferBuilder::new()
    .context(pro_que.context())
    .dims(1)
    .build().unwrap();
```

Looks like it gives the same result:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OpenCL version too low to use this feature (detected: 1.1, required: 1.2).', /checkout/src/libcore/result.rs:860:4```

**Comment by c0gent** [comment]
Mind posting the stack trace?

**Comment by AdamNiederer** [comment]
```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  11: opencl_rs::main
             at src/main.rs:23
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  14: main
  15: __libc_start_main
  16: _start

```

**Comment by c0gent** [comment]
Ah right... nevermind.

I'm not sure which function `BufferBuilder::build` or `Buffer::new` could be calling which would trigger the error you're getting other than `::enqueue_fill_buffer`. The error message probably needs to include that.

Strange... I'll look into it as soon as I can.

**Comment by c0gent** [comment]
I still have no idea how you were getting the 'version too low' message by creating a buffer with no fill value but I [added extra error text](https://github.com/cogciprocate/ocl-core/commit/fcba93e1307fbc7fa19701e3f13a023cd64e2802) which will indicate the source of version errors. 

I also went ahead and [added fill functionality for OpenCL 1.1](https://github.com/cogciprocate/ocl/commit/e979462f58e2cde1bddda554ef338ed63a559c9d).

Go ahead and update your ocl dependency to this repo (or git pull your local clone) when you get a chance and let me know if the problem is fixed. If not, please paste the new error text.

**Comment by AdamNiederer** [comment]
Thanks a bunch for working on this so quickly!

Unfortunately, I'm still getting the error. Here's everything I have at the moment:

```rust
extern crate ocl;
use ocl::ProQue;
use ocl::builders::BufferBuilder;

fn main() {
    let src = r#"
        __kernel void add(__global float* buffer, float scalar) {
            buffer[get_global_id(0)] += scalar;
        }
    "#;

    let pro_que = ProQue::builder()
        .src(src)
        .dims(1 << 20)
        .build().unwrap();

    let buffer = BufferBuilder::<f32>::new()
        .context(pro_que.context())
        .dims(1)
        .build().unwrap();
    // let buffer = pro_que.create_buffer::<f32>().unwrap();

    let kernel = pro_que.create_kernel("add").unwrap()
        .arg_buf(&buffer)
        .arg_scl(10.0f32);

    kernel.enq().unwrap();

    let mut vec = vec![0.0f32; buffer.len()];
    buffer.read(&mut vec).enq().unwrap();

    println!("The value at index [{}] is now '{}'!", 200007, vec[200007]);
}
```

```
[package]
name = "opencl-rs"
version = "0.1.0"
authors = ["Adam Niederer <Adam.Niederer@gmail.com>"]

[dependencies]
ocl = { git = "https://github.com/cogciprocate/ocl" }

[replace]
"cl-sys:0.3.0" = { git = "https://github.com/cogciprocate/cl-sys" }
"ocl-core:0.5.1" = { git = "https://github.com/cogciprocate/ocl-core" }
```

```bash
$ cargo build --release
   Compiling libc v0.2.29
   Compiling crossbeam v0.2.10
   Compiling semver v0.1.20
   Compiling bitflags v0.8.2
   Compiling odds v0.2.25
   Compiling futures v0.1.14
   Compiling num-traits v0.1.40
   Compiling rustc-serialize v0.3.24
   Compiling cl-sys v0.3.0 (https://github.com/cogciprocate/cl-sys#6d74aee4)
   Compiling rand v0.3.16
   Compiling nodrop v0.1.9
   Compiling rustc_version v0.1.7
   Compiling num-integer v0.1.35
   Compiling enum_primitive v0.1.1
   Compiling ocl-core v0.5.1 (https://github.com/cogciprocate/ocl-core#fcba93e1)
   Compiling qutex v0.1.1
   Compiling num-iter v0.1.34
   Compiling num-complex v0.1.40
   Compiling num-bigint v0.1.40
   Compiling num-rational v0.1.39
   Compiling num v0.1.40
   Compiling ocl-core-vector v0.1.0 (https://github.com/cogciprocate/ocl-core#fcba93e1)
   Compiling ocl v0.14.1 (https://github.com/cogciprocate/ocl#e979462f)
   Compiling opencl-rs v0.1.0 (file:///home/adam/opencl-rs)
    Finished release [optimized] target(s) in 45.1 secs
$ ./target/release/opencl-rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ::get_kernel_arg_info: OpenCL version too low to use this feature (detected: 1.1, required: 1.2).', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: opencl_rs::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  13: __libc_start_main
  14: _start
```

**Comment by c0gent** [comment]
I see... it's due to the way `Kernel` automatically compares argument types with those specified in the kernel program.

I'll add a bypass for that.

**Comment by c0gent** [comment]
https://github.com/cogciprocate/ocl/commit/0b4df19ea8519e10a450d91a488277b5abe66ab3 should do the trick.

**Comment by AdamNiederer** [comment]
```
The value at index [200007] is now '10'!
```
Awesome, thank you!

**Comment by c0gent** [comment]
Thank you for helping debug this :)
